# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "Capistrano-Slack"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Stuart Watson"]
  s.date = "2014-05-16"
  s.description = "This gem integrates Capistrano with slack"
  s.email = "stuart.watson@unep-wcmc.org"
  s.files = [
    "Capistrano-Slack.gemspec",
    "Rakefile",
    "VERSION",
    "lib/capistrano_slack/capistrano_slack.rb",
    "lib/capistrano_slack/common.rb",
    "pkg/Capistrano-Slack-0.0.1.gem"
  ]
  s.homepage = ""
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Capistrano Slack Integration"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

